arch:
  - amd64
  - ppc64le
language: python
python:
  - 2.7
  - 3.6
  - 3.7
before_install:
  # Escape Travis virtualenv
  - deactivate
  # See: http://conda.pydata.org/docs/travis.html
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install pip nose coverage numpy scipy matplotlib Cython
  - pip install nose-cov
install:
  - python setup.py sdist
  - mkdir empty
  - cd empty
  - pip install ../dist/*
  - INSTALLDIR=$(python -c "import os; import colorspacious; print(os.path.dirname(colorspacious.__file__))")
script:
  - nosetests --all-modules --with-cov --cov-conf ../.coveragerc --cov-report term-missing --cov ${INSTALLDIR} colorspacious
after_success:
  - pip install codecov && codecov
notifications:
  email:
  - njs@pobox.com
